security:
  jwt:
    secret-key: verysecretkeydonottellanybody

management:
  endpoints:
    web:
      exposure:
        include: "*"

  server:
    port: 8090

#  http://localhost:8080/actuator/beans
#  http://localhost:8080/actuator/health